# 🚀 CPP Module 05

---

## 📌 Introduction 
This project is the sixth module of the C++ Piscine at 42. It introduces exception handling in C++,
exploring how to write robust and fault-tolerant programs using try-catch blocks and custom exceptions.

---

## 📚 Topics Covered
- Exception Handling (try, catch, throw)
- Standard Exceptions in C++
- Creating and Handling Custom Exceptions
- Proper Error Management

---

## 📂 Project Structure
```bash
CPP05/
│── ex00/
│── ex01/
│── ex02/
│── ex03/
```

Each exercise contains a separate task designed to reinforce the module's concepts.

## ⚙️ Compilation & Execution 
To compile a specific exercise, navigate to its directory and run:
```bash
make
./<executive_name>
```
